Sorting/Java/MergeSort.java
MergeSort algorithm implemented in Java
=> MergeSort.java

Sorting/Java/InsertionSort.java
Insertion Sort algorithm implement in java Here are the screenshots for some test cases Program
=> Insertion Sort algorithm implement in java

Data_Structures/Java/SinglyLinkedList.java
Singly Linked List implemented in Java.
Here are the Sample screenshots
=> SinglyLinkedList.java

Data_Structures/Stack.java
Stack class implemented in Java.  Here are the screenshots
=> Stack.java

Sorting/C++/Heap_Sort.cpp
Implementation of Heap_Sort by taking input from the user and using a max heap for this implementation.
=> Heap_Sort.cpp

LICENSE
Create an explicit LICENSE file in the project. Many people will require this before contributing to projects at all.
=> Creating explicit LICENSE (Issue 41)

Searching/Binary_Search/C++/BinarySearch.cpp, Searching/Binary_Search/C/BinarySearch.c, Searching/Binary_Search/Java/BinarySearch.java, Searching/Binary_Search/Python/BinarySearch.py, Searching/Binary_Search/README.md
Here are some standard implementations of the Binary Search algorithm. 
As mentioned earlier, I have also added a README in the folder for easy information access. If this looks fine, we could do this for other algorithms as well.
=> Added Binary Search implementations in C, C++, Java and Python (Issue 42)

CODE_OF_CONDUCT.md
Adding standard Contributor Covenant Code of Conduct. Fixes #49
=> Create CODE_OF_CONDUCT (Issue #49)

Sorting/Heap Sort/HeapSort.java
* Implement HeapSort Algorithm in Java 
* This resolves the issue #57
=> Implemented HeapSort Algorithm in Java

.github/ISSUE_TEMPLATE/add-algorithm.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/improve-an-algorithm.md
Added issue templates. Fixes #130
=> [URGENT] Add issue templates (Issue #130)

Java Design Patterns/DAO pattern/DaoPatternDemo.java, Java Design Patterns/DAO pattern/Student.java, Java Design Patterns/DAO pattern/StudentDao.java, Java Design Patterns/DAO pattern/StudentDaoImpl.java
=> Add DAO java design pattern

Java Design Patterns/DAO pattern/README.md
Fixes issue #145 
Added a documentation for DAO design pattern in Java
=> Add readme for DAO design pattern

Graphs/cpp/dijkstra_shortest_path.cpp, Graphs/dijkstra_shortest_path.cpp
Closes #82
Added Dijkstra's shortest path algorithm
#82 
Build .cpp using g++ and run the executable
=> Added dijkstra shortest path algorithm

Java Design Patterns/Singleton/README.md
fixes issue #152
Added Readme for Singleton Design Pattern in Java
=> Added Readme for Singleton Design Pattern in Java

Sorting/Selection Sort/README.md
=> Readme for selection sort 

Data Structures/BST/Java/BST.java, Data Structures/BST/Java/BSTInterface.java, Data Structures/BST/Java/BSTTest.java, Data Structures/BST/Java/Node.java
Add BST Implementation using Java Language #90
=> Add BST implementation in Java Language

Sorting/Selection Sort/python/selection_sort.py
Added selection sort in Python.
=> Added Selection Sort in Python fixed #113

Java Design Patterns/AbstractFactory/App.java, Java Design Patterns/AbstractFactory/FactoryCar.java, Java Design Patterns/AbstractFactory/GMCFactory.java, Java Design Patterns/AbstractFactory/Minivan.java, Java Design Patterns/AbstractFactory/Pickup.java, Java Design Patterns/AbstractFactory/Savana.java, Java Design Patterns/AbstractFactory/Sienna.java, Java Design Patterns/AbstractFactory/Sierra.java, Java Design Patterns/AbstractFactory/Tacoma.java, Java Design Patterns/AbstractFactory/ToyotaFactory.java, Java Design Patterns/AbstractFactory/readme.md
#185
new Implementation for Abstract Factory in JAVA
#185 
Compile and execute the class `App.java`
=> feat(Abstract Factory): added new Implementation for Abstract Factory

Dynamic Programming/coin_change_problem.cpp, Dynamic Programming/coin_change_problem/C++/coin_change_problem.cpp, Dynamic Programming/coin_change_problem/README.md
Added a file named coin_change_problem.cpp containing 
1. The question at the top of the file.
2. Code solving the problem statement
Related issue #99 
Solved the question on interviewbit with all the test cases passing.
=> added code for coin change problem

Sorting/Insertion Sort/Scala/InsertionSort.scala
Added insertion sort implementation in Scala.
https://github.com/Asiatik/codezilla/issues/172
=> #172 added insertion sort implementation in Scala

Dynamic Programming/dp_ways_to_decode.cpp, Dynamic Programming/ways_to_decode/C++/dp_ways_to_decode.cpp, Dynamic Programming/ways_to_decode/README.md
Added a file named dp_ways_to_decode containing 
1. The question at the top of the file.
2. Code solving the problem statement
Related issue #147 
Solved the question on interviewbit with all the test cases passing.
=> added code for ways to decode

Sorting/Bubble Sort/C/BubbleSort.c
=> BubbleSort Implementation in C

Searching/Binary Search/Kotlin/BinarySearch.kt
Adding Binary Search program using Kotlin programming language.
=> Added Binary Search program using kotlin

Sorting/Quick Sort/Readme, Sorting/Quick Sort/Readme.md
Provided a readme document about quick sort
=> Readme about Quick sort

Maths/Factorial/C++/factorial.cpp, Maths/Factorial/C/factorial.c, Maths/Factorial/Java/Factorial.java, Maths/Factorial/Python/factorial.py, Maths/Factorial/README.md
Added factorial algorithms to Maths directory in C/C++/Java/Python
=> Factorial C/C++/Python/Java

CONTRIBUTING.md, runme.bh
* Added a bash file structure creator
#193 
Me manually running the programme. 
Maybe add documentation in the main readme
=> updated runme.bh

Sorting/Insertion Sort/C++/InsertionSort.cpp
I have added a new folder under Sorting as Sorting/C++.
I have added the InsertionSort.cpp file which contains the implementation for insertion sort.
Link to the issue here: https://github.com/Asiatik/codezilla/issues/228
The file added contains the function which runs the file and shows the output. This shows the working results for the algorithm. Thus, the algorithm can be tested using the `main` function in the same file.
=> Fix for issue #228 - Insertion sort in C++

Graphs/BFS/Python/bfs.py
Added implementation of BFS in Python
Issue #303
=> Add BFS in Python

Graphs/BFS/C++/BFS.cpp
Added implementation of BFS in C++
Issue #286
=> Add BFS in C++

LL.java
Fixes #311 
Added a file named LL.java 
Please review it!
=> Linked List Implementation

heap in java
=> Create heap in java

Sorting/QuickSort.java
=> Create Iterative QuickSort.java

Searching/Linear Search/Java/LinearSearch.java
The list of elements as well as the search element can be taken as the user input at runtime.
Proper and clear presentation of the code for the user.
For Example:
You …
=> List of elements and search element can be entered by the user

Maths/Factorial/C/factorial.c
=> input section is complete

Sorting/Bubble Sort/C/BubbleSort.c
=> input sectin in main function

Maths/Factorial/C#/Factorial.cs
Added a file "Factorial" that implements a factorial algorithm in C#.
https://github.com/Asiatik/codezilla/issues/343
Created a driver class (not included in this pull request since it would not be necessary) to run a few tests and compared the output with the expected result. Outputs matched expected outputs.
From my understanding, there shouldn't be any new documentation needed. If there is, please let me know.
=> Add C# factorial algorithm

Searching/Binary Search/README.md, Searching/Linear Search/README.md
Add best case of time complexity of any search to readme file
=> New information to readme file

Dynamic Programming/Fibonacci Sequence/Fibonacci_series.txt, Fibonacci_series.py, Maths/Fibonacci/Python/Fibonacci_series.txt
=> Fibonacci Series in python

Sorting/Heap Sort/Readme.md
Add a Readme file to Heap Sort
=> Add a Readme file to Heap Sort

Searching/Binary Search/C++/BinarySearch.cpp, Searching/Binary Search/C/BinarySearch.c, Searching/Binary Search/Python/BinarySearch.py
* Changed the algorithm for bugs.
fixing issue #393 
=> Fix binary search

Searching/Binary Search/PHP/BinarySearch.php
I've added a new file named BinarySearch.php that implements this algorithm in that language. 
#425  
- [ x] New Algorithm (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
=> Added new Binary Search algorithm in PHP

Bit Algorithms/Rotate Bits/C++/rotate_bits.cpp, Bit Algorithms/Toggle Bits/C++/toggle_bits.cpp
Added Bit-Based Algorithms Directory which currently consists of Toggle Bits and Rotate Bits 
algorithms. Will it more complex bit related algorithms once this feature is reviewed.
The issue raised is to make addition to the Bit-Based algorithms directory
Please link to the issue here: #469 
Manual tests were done to check for bit changes
=> added bit-based algorithms
